CREATE TABLE IF NOT EXISTS NOBEL_WIN(
YEAR INTEGER,
SUBJECT TEXT,
WINNER TEXT,
COUNTRY TEXT,
CATEGORY TEXT
);

INSERT INTO NOBEL_WIN (YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY) VALUES
(1970,'PHYSICS','HANNES','SWEDEN','SCIENTIST'),
(1970,'PHYSICS','LOUIS','FRANCE','SCIENTIST'),
(1971,'PHYSICS','PAUL','FRANCE','SCIENTIST'),
(1970,'CHEMISTRY','HAMELTON','SWEDEN','LINGUIST'),
(1971,'LITERATURE','BERNARD','GERMANY','ECONOMIST'),
(1971,'BIOLOGY','PHILIPS','USA','PRIME MINISTER'),
(1971,'PHYSIOLOGY','HANNAH','HUNGARY','SCIENTIST'),
(1971,'PHYSICS','PETER','CHILE','SCIENTIST');

SELECT * FROM NOBEL_WIN;
SELECT * FROM NOBEL_WIN WHERE SUBJECT NOT LIKE 'P%';
